### ISSUE TITLE
webida-server fails to start.

### ISSUE THREAD

**Issue by mukul-git** [webida/webida-server#112]
Following is the error log on console

2015-10-13 11:37:33-466 - debug: ------------------ End to load service ---------------------

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: SQLITE_CANTOPEN: unable to open database file

Moreover, on debug i found that it fails while trying to open src/server/sessions/sessions.db file.
Please provide some insights on how to solve it.

**Comment by gotchazipc** [comment]
Have you set right permission to the session directory to webida server process user, running unit-manager.js?  If fact, the sqlite3 session file is created by express.js middleware of auth unit server and there's no black-magic. You can set some other session directory with configuration (webida-server/conf/conf.js$/services/auth/sessionPath) and we recommend you to copy defaultConf.js to conf.js to update without conflict.

**Comment by mukul-git** [comment]
I had to create it manually using sqlite3 command. Though it should create that file on it's own if it's not present on first startup.
I guess sqlite process was not able to create sessions.db because it's parent folder(sessions) didn't exist.
Probably the fix should involve creating an empty sessions directory upon installation.

**Comment by gotchazipc** [comment]
Thank you. It seems that devil lives in detail and missing documentations. Anyway, We're implementing redis-based cache service & session store (will be available in several sprints), and current sqlite3-based session storage is just a simple, clumsy makeshift. We'll fix our bug soon.

**Comment by kyungmi** [comment]
I'll close this issue. You can reopen or raise other issue at any time.
