### ISSUE TITLE
Some FS APIs are not collected by profiler

### ISSUE THREAD

**Issue by darkain84** [webida/webida-server#114]
Current FS server's API profiler pattern is '\/webida\/api\/fs/[^\/]*'
I think that this pattern did not support below APIs:
- Get All file system info : GET '/webida/api/fs' 
- Create new file system : PUT '/webida/api/fs'
- FS Alias URL: GET '/webida/alias/aliasKey/..'

It seems to me a bug. Maybe or not. 
If it is a bug, Is there a plan to fix it???

**Comment by darkain84** [comment]
Below pattern has some problem, I think that it is better than original pattern.

original pattern:
'\/webida\/api\/fs\/[^\/]*'

new pattern:
'(\/webida\/api\/fs\/[^\/]*|' + '\/webida\/api\/fs|' + '\/webida\/alias\/|)'

Problem: 
GET/DELETE '/webida/api/fs/:fsid' APIs return '/webida/api/fs/each fsid' instead '/webida/api/fs/fsid'

**Comment by darkain84** [comment]
There was same issue on the auth service.

The pattern should be changed like below:
'(\/webida\/api\/oauth\/[^\/]*|' + '\/webida\/api\/acl\/[^\/]*|' + '\/webida\/api\/group\/[^\/]*|' + '.*)';

**Comment by gotchazipc** [comment]
We'll add patterns in 1.7.0.
