### ISSUE TITLE
Login with github, google or guest mode fails.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-server#115]
Sometimes, login with github, google or guest mode failes.

**Comment by kyungmi** [comment]
@JUHYUNCHOI In case of 'Google login', that was just caused by a recent network problem. But the reason of 'Github login' issue was more complicated and I resolved the issue with PR #116.
Unfortunately, I haven't gotten realize what is the real problem with the 'guest login' yet.

**Comment by kyungmi** [comment]
@JUHYUNCHOI I wrote #117 about remained 'guest login' issue.
You can try to login with Github or Google again.
