### ISSUE TITLE
'Remember my email' is not working.

### ISSUE THREAD

**Issue by lisyoen** [webida/webida-server#121]
In the login page,

1. Check 'Remember my email' box.
2. Input a correct email address.
3. Input a wrong password and enter.

Even though I checked 'Remember my email' box, e-mail is deleted after submitted a wrong password.

**Comment by gotchazipc** [comment]
Move email address to local storage. avoid using cookie.

**Comment by JUHYUNCHOI** [comment]
Email address is still removed when I typed wrong password.

**Comment by kyungmi** [comment]
I planned to do this with the local storage on the next sprint.

**Comment by kyungmi** [comment]
This isn't a thing about the feature of 'Remember Me'. I'll create another issue with clearing up the point.
