### ISSUE TITLE
Improve server performance

### ISSUE THREAD

**Issue by hwshim** [webida/webida-server#126]
Loading https://webida.net/pages/main.html takes avg. 5 seconds.
Even, creating project takes 10 secs more.
We should find the reason for this.
Then we should solve easy one first.

**Comment by gotchazipc** [comment]
Introduced redis #110 (Apply Redis)  has been done in PR #144. 
Next goal is to reduce requests for opening workspaces.

**Comment by gotchazipc** [comment]
We've speed up server many times :)
