### ISSUE TITLE
replace node ffi over libattr-dev package to node fs-xattr package 

### ISSUE THREAD

**Issue by gotchazipc** [webida/webida-server#138]
We may can use sys/xattr.h from glibc. Why should we install libattr-dev manually?

**Comment by gotchazipc** [comment]
We decided to remove features with metadata that relies on xattr of file system. The metadata should be handled with DB, not FS, for easy indexing & backup. (xattr will not be copied acrossing partitions and most of simple backup tools like rsync may not sync attributes) we'll remove the feature in next sprint.

**Comment by wcho** [comment]
FYI. Xattrs are not copied as default even within a partition. But there are options that you can copy/rsync/backup with xattrs.

**Comment by gotchazipc** [comment]
Thanx for the information. We'll debate on this issue at the end of this sprint again.

**Comment by gotchazipc** [comment]
metadata api will be removed in webida 2.x
current metadata api may not be changed no more for there's no significant errors.
