### ISSUE TITLE
add batch module upstart configuration 

### ISSUE THREAD

**Issue by gotchazipc** [webida/webida-server#141]
need start webida-batch; stop webida-batch.

**Comment by gotchazipc** [comment]
please, close this issue after applying the upstart configuration in our servers

**Comment by kyungmi** [comment]
@gotchazipc I applied this upstart script on both servers. But the batch server starts with an error in weibda.org server.

```
args :  svc=batch0
svc
2015-11-17 07:14:34-530 - debug: run in single process
2015-11-17 07:14:34-532 - debug: main module dir = /home/webida/webida-server/webida.org/server
error: Forever detected script exited with code: 0
error: Script restart attempt #5
```

Please check it.

**Comment by gotchazipc** [comment]
fixed
