### ISSUE TITLE
fix jshint configurations 

### ISSUE THREAD

**Issue by gotchazipc** [webida/webida-server#145]
1) support ES6 grammars with esnext=true
2) turn off some meaningless rules like curly braces & single quotation mark
3) increase maxlen to 136. (120 is too short)
4) let  latedef be true. let's move to let/const from stupid 'var' 
5) we need a separated jshint file for conf directory. JSON usually requires more relaxed rules, especially with camelcase & white spaces.

**Comment by wcho** [comment]
Will you fully adopt ES6 in the server code?
And I think line length 120 is long enough (or too long). Almost all the coding convention guides say lengt length should be less than 80 or 100.

**Comment by gotchazipc** [comment]
We are now adopting some ES6 syntaxes that is supported natively (without shimming) in Node 4.2.
And... line length is not important. Nobody uses dummy terminals today, and we may need some different number from 80 for code diff / review tools. 

Anyway, since .jshintrc file that is used for checking PR is not a part of server source code.
