### ISSUE TITLE
deleteAccount() api bug

### ISSUE THREAD

**Issue by sangjin3** [webida/webida-server#161]
When deleteAccount() api is called, server currently check an authorization with query.uid
But the query.uid is a target to delete, not a target to check authorization.
Server should check the user who is requesting the deleteAccount() api have an authority to do it or not.

**Comment by kyungmi** [comment]
@sangjin3 I looked into the `user-manager.js` source. But checkAuthorize() seems be done with the `req.user.uid`, not `req.query.uid`.
Could you explain more about this?

**Comment by sangjin3** [comment]
I mean deleteAccount() implementation, not a checkAuthorize() api. 
(src/server/auth/lib/user-manager.js:729)

**Comment by kyungmi** [comment]
Finally it turned out that it has no problem. I'll close this issue.
