### ISSUE TITLE
failed login when installed a specific chrome plug-in

### ISSUE THREAD

**Issue by hyunjongpark** [webida/webida-server#72]
Failed login and displayed as "access token : 3" after installed the chrome plug-in.
Chromium of plug-in message will arrive earlier than the message of the auth server .

chrome plug-in : https://chrome.google.com/webstore/search/Grammarly%20Spell%20Checker%20%26%20Grammar%20Checker?hl=ko

**Comment by kyungmi** [comment]
Related with: WSDK-612

**Comment by kyungmi** [comment]
@hyunjongpark I cannot reproduce the problem.

**Comment by hyunjongpark** [comment]
I do not even be able to reproduce the problem.
